[package]
name = "tp3-4"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
hex = "0.4.3"
hex-literal = "0.4.1"
inquire = "0.7.5"
itertools = "0.13.0"
sha1 = "0.10.6"
sha2 = "0.10.8"
text_io = "0.1.12"
